name: Lightsail Publish
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        uses: montudor/action-zip@v1
        with:
         args: zip -qq -r fw-site-archive.zip .
      - name: Upload zip archive to S3 bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: ./fw-site-archive.zip
          AWS_ACCESS_KEY_ID: ${{ secrets.CODEDEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CODEDEPLOY_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          S3_BUCKET: 'fw-code-deploy'
          S3_KEY: 'fw-site-archive.zip'
