name: Lightsail Publish
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        uses: montudor/action-zip@v1
        with:
         args: zip -qq -r build.zip .
      - name: Upload infrastructure files to S3 bucket
        uses: eonx-com/actions-s3-copy@v1.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.CODEDEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CODEDEPLOY_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          DESTINATION_BUCKET: "fw-code-deploy"
          SOURCE_PREFIX: "build"
          SOURCE_SUFFIX: ".zip"
          DESTINATION_PREFIX: ""
          DESTINATION_SUFFIX: ""
          TIMESTAMP: "true"

